---
openapi: 3.0.3
info:
  title: String Controller
  description: |-
    This service performs string operations.
  version: 1.0.0
tags:
  - name: String Operator
    description: Basic string operations.
paths:
  /upper:
    get:
      tags:
        - string operator
      summary: Makes string upperCase.
      description: makes String upper case
      operationId: upper
      parameters:
        - name: String
          in: query
          required: true
          schema:
            type: string
          example: hallo

      responses:
        '200':
          description: Successful operation.
          content:
            text/plain:
              schema:
                type: string
              example: HALLO